#index:
#    path: /
#    controller: App\Controller\DefaultController::index

hello:
    path: /hello-world
    controller: App\Controller\HomeController::hello

profilUser:
    path: /profil
    controller: App\Controller\UserController::profil

compteUser:
    path: /compteUser
    controller: App\Controller\UserController::compteUser